// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyC2D46a2zwoHzczVNJGf88NvBW4J-F6ScM',
//     appId: '1:955293329662:web:28268238b3cb2779bd1daf',
//     messagingSenderId: '955293329662',
//     projectId: 'mylegend-7bc81',
//     authDomain: 'mylegend-7bc81.firebaseapp.com',
//     storageBucket: 'mylegend-7bc81.appspot.com',
//     measurementId: 'G-N00X7J8ZVN',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBJYQceWc8T_3G1TfCySZAY1O_Xi1zY-AE',
//     appId: '1:955293329662:android:7c510c006832b473bd1daf',
//     messagingSenderId: '955293329662',
//     projectId: 'mylegend-7bc81',
//     storageBucket: 'mylegend-7bc81.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyA0JvYThL4ttQspPdx1yKTZqt4ErICy3BQ',
//     appId: '1:955293329662:ios:6e5f281038700c74bd1daf',
//     messagingSenderId: '955293329662',
//     projectId: 'mylegend-7bc81',
//     storageBucket: 'mylegend-7bc81.appspot.com',
//     iosClientId: '955293329662-7s77dtl8jtl46bb6fqt7nc75p8pha3vf.apps.googleusercontent.com',
//     iosBundleId: 'com.legend.my.legend',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyA0JvYThL4ttQspPdx1yKTZqt4ErICy3BQ',
//     appId: '1:955293329662:ios:6e5f281038700c74bd1daf',
//     messagingSenderId: '955293329662',
//     projectId: 'mylegend-7bc81',
//     storageBucket: 'mylegend-7bc81.appspot.com',
//     iosClientId: '955293329662-7s77dtl8jtl46bb6fqt7nc75p8pha3vf.apps.googleusercontent.com',
//     iosBundleId: 'com.legend.my.legend',
//   );
// }
